/* This is for purpose only, just for testing, because Mootools needs a real JSONP service, this can work just because we call a known function (NS_Requester.onComplete), but this isn't work with all the Mootools JSONP events (onComplete is never fired and you can't chain a request). */

NS_Requester.onComplete({"items":[
	{"title":"Roms : \"Huit ans qu'on joue au chat et à la souris\", dit un maire\n","tag":"politique","time":"17h08","picture":"http://media.rtl.fr/online/image/2013/0925/7764792839_des-roms-sont-expulses-de-leur-campement-a-lille-le-5-juin-2013.jpg"},
	{"title":"\"On voit vraiment comment ça se passe sur le terrain\", dit un élève\n","tag":"société","time":"16h55","picture":"http://media.rtl.fr/online/image/2013/0305/7759108070_francois-hollande-a-prone-une-acceleration-de-l-acces-des-chomeurs-a-la-formation-professionnelle.jpg"},
	{"title":"\"Je veux vivre comme les Français\" explique Yohan\n","tag":"politique","time":"12h08","picture":"http://media.rtl.fr/online/image/2013/0925/7764792314_des-roms-dans-un-campement-parisien-photo-d-illustration.jpg"},
	{"title":"Mamère quitte EELV : \"Il s'est isolé depuis des années\", juge Voynet","tag":"politique","time":"16h14","picture":"http://media.rtl.fr/online/image/2013/0925/7764799279_noel-mamere-et-dominique-voynet.jpg"},
	{"title":"Pakistan : la ville d'Awaran détruite par un puissant séisme","tag":"international","time":"16h37","picture":"http://media.rtl.fr/online/image/2013/0925/7764799571_des-habitations-ont-ete-entierement-detruites-par-le-seisme-pres-de-la-ville-d-awaran.jpg"},
	{"title":"Valenciennes-PSG, Monaco-Bastia : la lutte à distance reprend\n","tag":"football","time":"12h46","picture":"http://media.rtl.fr/online/image/2013/0809/7763667508_edinson-cavani-a-fait-ses-debuts-en-l1-en-seconde-periode-mais-n-a-pas-marque.jpg"},
	{"title":"Adil Rami : exclu par Valence, son avenir en Bleu se complique","tag":"football","time":"16h51","picture":"http://media.rtl.fr/online/image/2013/0925/7764799205_adil-rami-reportera-t-il-le-maillot-de-valence.jpg"},
	{"title":"Bartoli félicite l'OM... et promet de ne plus aller au Vélodrome","tag":"insolite","time":"14h22","picture":"http://media.rtl.fr/online/image/2013/0806/7763605966_marion-bartoli-a-donne-le-coup-d-envoi-du-match-amical-marseille-porto-le-13-juillet-2013.jpg"},
	{"title":"Tony Parker, 4e meilleur joueur NBA pour Sports Illustrated","tag":"basket","time":"17h20","picture":"http://media.rtl.fr/online/image/2013/0925/7764800083_tony-parker-sous-le-maillot-des-spurs-de-san-antonio.jpg"},
	{"title":"Louboutin veut faire interdire une campagne anti-islam","tag":"info","time":"17h19","picture":"http://media.rtl.fr/online/image/2013/0925/7764801867_une-chaussure-louboutin-arborant-la-celebre-semelle-rouge.jpg"},
	{"title":"Arnaud Montebourg présente ses excuses à Florence Woerth","tag":"info","time":"16h46"},
	{"title":"Nantes : démantèlement d'une filière de fausses cartes bleues","tag":"info","time":"15h59","picture":"http://media.rtl.fr/online/image/2013/0925/7764799205_adil-rami-reportera-t-il-le-maillot-de-valence.jpg"},
	{"title":"Roms : Bruxelles menace à nouveau Paris de sanctions","tag":"info","time":"15h47","picture":"http://media.rtl.fr/online/image/2013/0925/7764799191_viviane-reding-vice-presidente-de-la-commission-europeenne-chargee-de-la-justice.jpg"},
	{"title":"La momie mystère était en plastique","tag":"info","time":"15h20","picture":"http://media.rtl.fr/online/image/2013/0903/7764265186_la-momie-retrouvee-dans-un-grenier-de-diepholz-en-allemagne.jpg"},
	{"title":"Élections européennes : la date fixée au 25 mai","tag":"info","time":"14h48","picture":"http://media.rtl.fr/online/image/2013/0925/7764797330_les-francais-seront-appeles-a-voter-le-dimanche-25-mai-2014.jpg"},
	{"title":"Budget 2014 : ce qui va baisser","tag":"info","time":"14h26","picture":"http://media.rtl.fr/online/image/2013/0925/7764796344_bernard-cazeneuve-et-pierre-moscovici-mercredi-25-septembre.jpg"},
	{"title":"Budget 2014 : ce qui va augmenter","tag":"info","time":"14h25","picture":"http://media.rtl.fr/online/image/2013/0925/7764795117_bernard-cazeneuve-et-pierre-moscovici-presentant-le-projet-de-lois-de-finances-2014-mercredi-25-septembre.jpg"},
	{"title":"Disparition de Fiona : la version de la mère mise à mal par le troisième gardé à vue","tag":"info","time":"14h13","picture":"http://media.rtl.fr/online/image/2013/0517/7761489815_fiona-5-ans-a-disparu-dimanche-12-mai-2013.jpg"},
	{"title":"Disparition de Fiona : deux gardes à vue supplémentaires à Clermont-Ferrand","tag":"info","time":"13h57","picture":"http://media.rtl.fr/online/image/2013/0925/7764783413_fiona-5-ans-a-disparu-dimanche-12-mai-2013-alors-qu-elle-jouait-dans-un-parc-public-de-clermont-ferrand.jpeg"}],
	"show":{"name":"Les Grosses Têtes","startTime":"16h00","endTime":"18h00","video":false,"speakers":["Philippe Bouvard"]}})